version: '3.9'
services:
  web_scraping:
    build:
      context: .
      dockerfile: scraping-service/Dockerfile
    # command: bash -c "python manage.py makemigrations && python manage.py migrate"
    ports:
      - 8002:8000
    volumes:
      - ./scraping-service:/app
    env_file:
      - .env
  backend_auth:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # command: bash -c "python manage.py makemigrations && python manage.py migrate"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    env_file:
      - .env
  backend_company:
    build:
      context: .
      dockerfile: backend_company/Dockerfile
    # command: bash -c "python manage.py makemigrations && python manage.py migrate"
    ports:
      - 8001:8000
    volumes:
      - ./backend_company:/app
    env_file:
      - .env
  web:
    build: frontend/admin/template/template_react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/admin/template/template_react:/frontend
    depends_on:
      - backend_auth
      - backend_company
    env_file:
      - .env
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444